### ISSUE TITLE
Printing top-level expressions to Interactions Area

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#1]
Point: Expressions in the definitions window *should* print their results in the interactions window. This is one area where a lot of our pedagogy assumes a particular behavior on the part of the tool, and where there are serious consequences for changing the behavior from WeScheme. 

Counterpoint: when you have modules requiring modules, the dependency graph may pull in tons of stuff littered with top-level expressions. Printing all these to the interactions window is confusing and bad.

I believe that Shriram, Joe, Ben and I reached a good decision on this point: modules could contain top-level expressions, but the only ones that print are the ones in the definitions window. Maybe this behavior will come for free once the new module system lands, but I wanted to track it here as well.

**Comment by ds26gte** [comment]
Fixed in 731b6a9.

**Comment by schanzer** [comment]
Hell yes!!!!!

**Comment by schanzer** [comment]
This is already implemented in horizon, so we should just hook into that.

**Comment by schanzer** [comment]
Merged now that we're tracking horizon
