### ISSUE TITLE
Implementing (require ....) 

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#11]
`(require ...) ` needs more discussion.

Some design proposals:
1) We will always need the ability to import teachpacks/modules in some form for Bootstrap:1. I'm assuming it's a much easier design philosophy to say that racket programs can only require modules written in racket, yes?

2) However, with the move to GDrive, it seems fair to say that the only files that can be required are either built-ins (ie - "bootstrap2012/bootstrap-teachpack") or those with a Drive ID. Agreed?

3) This means there are two dependencies on this issue: making the built-in modules available in Spyret, and setting up the GDrive integration to allow for opening/saving .rkt files.

For the mid-to-long-term future, I'd like to allow require to still take wescheme/XYZ as an argument. This would then load a shared file from wescheme.org, allowing us to leverage user-created teachpacks and smooth the transition down the road.

**Comment by ds26gte** [comment]
e5adcc4 now contains an implementation of `require` that works with the `src/web/collections` directory, which is newly included (copied over from the `wescheme2012` repo). E.g.,

```
(require "bootstrap/autos.ss")
```

loads `.../web/collections/bootstrap/autos.ss`, ensuring that only the `provide`d identifiers in it are visible outside.

(Known problem: Some of the other builtin module files in the `collections` currently fail to load because of use of obsoleted character and symbol syntax. Will fix.)

**Comment by schanzer** [comment]
Not sure if I'm following you correctly, but the following does not work:
`(require "bootstrap2015/bootstrap-teachpack")`

(Tried with and without quotes)

**Comment by ds26gte** [comment]
The extension `.ss` is required: `(require "bootstrap2015/bootstrap-teachpack.ss")`.

I tried it myself, and I had to change quoted Scheme-like symbols to strings, but even so, it uses three undefined globals `procedure-arity`, `compose`, and `RESTING-TOP-DOWN-ORIENTATION`, none of which are in the WeScheme documentation tab. I can figure out the first two, but what is the third one?

**Comment by ds26gte** [comment]
Added `apply`, `compose`, `procedure-arity`, and `pair?` in 3d99b1b and ds26gte/pyret-lang@9f44f00. Also modified `bootstrap2015/bootstrap-teachpack.ss` in cf92a65 to use strings instead of symbols. 

This makes

```
(define RESTING-TOP-DOWN-ORIENTATION 40)
(require "bootstrap2015/bootstrap-teachpack.ss")
```

work.  (`RESTING-TOP-DOWN-ORIENTATION` has to be pre-defined.)

**Comment by schanzer** [comment]
Interesting - why require the `.ss`? That's a change in behavior from WeScheme, which means a higher bar for justification.

Also, running a regular [Bootstrap game](http://www.wescheme.org/view?publicId=PWqVwta8Dr) - even with ```(define RESTING-TOP-DOWN-ORIENTATION 40)
(require "bootstrap2015/bootstrap-teachpack.ss")``` 
at the top seems to fail due to some kind of strange static analysis bug

**Comment by ds26gte** [comment]
- `require` argument doesn't (and shouldn't) use the `.ss` extension. Enclosure within double quotes optional.
- removed arity restriction on functional arguments of `apply`, `compose`, `map`, `andmap`, `ormap`. (Bootstrap modules contain `apply`s with large numbers of args.)
- added `collections/tests` subdirectory containing regression suites.
- revisited bubbling order in final block: for every toplevel non-function def, determine if it refers to a local function def, and bubble accordingly. (Bootstrap modules contain both types of toplevel non-function defs, hence this.)
- `(require bootstrap2015/game)` for convenient one-shot testing of `bootstrap-teachpack`.

**Comment by schanzer** [comment]
Fantastic - I'm still amazed by how much _smoother_ everything is on Spyret than on WeScheme! 👍 

Also, I realized that some of the bugs I was seeing (including `RESTING-TOP-DOWN-ORIENTATION`) were due to some sloppy copy-pasting on my part, when I generated the 2015 teachpacks. I've pushed an update to those teachpacks (https://github.com/bootstrapworld/wescheme2012/commit/adb1eb4ab1d2d26fb93c1acfc2420561f8cadd79) that address the issue, so folding those into Spyret should allow regular Bootstrap games to run unmodified with the latest teachpack.

**Comment by schanzer** [comment]
The teachpacks are designed to do some basic testing of user-defined functions, in order to give some feadback before dying with a useless stack trace into the teachpack.

On WeScheme, I can trigger one of these errors by changing `update-danger` to consume three arguments. WeScheme will print out a predefined error message (from the teachpack) before the stack trace. Spyret, however, dies with an internal error:
![image](https://cloud.githubusercontent.com/assets/77126/14783444/aa04bfc8-0abd-11e6-8e4f-c8e9bb15bbac.png)

**Comment by ds26gte** [comment]
This was because of a missing `error` procedure. Fixed in fca288a and ds26gte/pyret-lang@13851ab.

Note `error` has a dual signature (even though the WeScheme documentation suggests not).  `error` can either take
- a single string argument; or
- a symbol (in Spyret, a string), followed by a format-string, followed by as many arguments as required by the format string

**Comment by schanzer** [comment]
*Beautiful*! Once the spyret teachpacks are updated, we should be all set!

**Comment by schanzer** [comment]
Since this issue has come to mean multiple things, I'm going to close it and open a separate one for the part that remains.
