### ISSUE TITLE
Trivial: args are swapped in fold/foldr

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#12]
`(define lst (list "hello" "goodbye"))
(define (f str acc) (string-length str))
(foldr f 0 lst)`

Gives 5 in WeScheme, but an error in Pyret. Swapping the inputs to `f` makes it work in Pyret, but not in WeScheme.

**Comment by ds26gte** [comment]
Which of Pyret vs WeScheme should change their behavior? I can't imagine we'd want to maintain different ``fold``ing behavior for the two languages?

**Comment by schanzer** [comment]
Neither.
Can you map racket's fold to something like `_spyret_fold`, and have that do the input swapping?

**Comment by ds26gte** [comment]
Done in ds26gte/pyret-lang@67471fb and 8897419.

**Comment by schanzer** [comment]
Confirmed - thanks!
