### ISSUE TITLE
Pyret disallows the use of new as an identifier

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#14]
`(define new 1)` should work

**Comment by schanzer** [comment]
Ditto for `debug`

**Comment by ds26gte** [comment]
Fixed in 0f969d1. I expect a few more such exceptional ids will be found in time, and they can all be similarly treated by expanding the concerned regexp.

**Comment by schanzer** [comment]
Awesome. Thanks!!
