### ISSUE TITLE
Mutually-recursive functions are not allowed

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#19]
`(define (f x) (g x))
(define (f x) (g x))`

Works in WeScheme, but not in Pyret (due to semantic differences).

**Comment by schanzer** [comment]
Right now this causes an internal error with no other information. At the very least, we should fail gracefully.

Curious to know if actually _supporting_ this feels any more achievable, now that you've been working on Spyret for almost a year and may have learned some new tricks.

**Comment by ds26gte** [comment]
This got fixed along the way.  Try

```
(define (eeven n) (if (= n 0) true (oddd (- n 1))))
(define (oddd n) (if (= n 0) false (eeven (- n 1))))
```

for a more visible indication that correctness is happening than an infinite loop.

**Comment by schanzer** [comment]
SWEET!!!!! Nice job.
