### ISSUE TITLE
struct definition is broken

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#20]
`(define-struct x ())` throws an error: `predicateId is not defined`

Do you have a test library you use? We should be able to catch regressions like this, and I worry about having to go back and re-run all my tests manually every time something changes.

**Comment by ds26gte** [comment]
Sorry, lame typo: wrote `predicateId` as `predictateId` while adding (not advertised) ``require``-related code.  Fixed in f0c4530.

Using regression file now for old fixes.
