### ISSUE TITLE
sin(n*pi) is incorrect

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#23]
Looks like another instance of JS bugs leaking through our js-numbers implementation. `(sin (* n pi))` is nonzero for all integer values of `n`, even though it should be zero. This problem also exists in CPO.

**Comment by ds26gte** [comment]
By non-zero, do you mean a very small non-zero number? That can't be helped, right, because of the unavoidable imprecision in pi? Even Racket's `(sin (* n pi))` returns a small nonzero number...

**Comment by schanzer** [comment]
Can we make an attempt to catch common cases, such as whole-number multiples of pi returning zero?

**Comment by ds26gte** [comment]
I don't think it's possible. The imprecise value of `pi` is indistinguishable in a call-by-value language from the same value presented as _das Ding an sich_ [1], where the non-zero result would be accurate and so should not be emended.

[1] In other words, we "Kant" do it...

**Comment by schanzer** [comment]
If I'm following you correctly, then, you're saying that a partially-patched hole is worse than no patch at all, since we'd be introducing a degree of inconsistency?

What's odd to me is that `(cos pi)` seems to work just fine.

**Comment by ds26gte** [comment]
Not odd if you look at their graphs. `cos x` for an input interval around `pi` ranges over a much narrower output interval than does `sin x` for the same input interval. 

Think of it this way: `d/dx (cos x)` near `pi` is around 0, meaning `cos x` doesn't change much in that neighborhood, meaning it must already be _very close_ to -1, meaning our number library will more readily approximate it to -1. 

`d/dx (sin x)` near `pi`, on the other hand, is around -1, so the sine for our unavoidable approximation of `pi` won't be quite as close to 0.

**Comment by schanzer** [comment]
I think we'll wind up revisiting this later when it comes to _other_ Very Small Values, but the issue itself is now addressed. Closing.
