### ISSUE TITLE
Passing tests don't highlight

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#34]
In the definitions window, write `(EXAMPLE 1 1)`, and click Run.

Try to click on the passing test in the test report. 
**Expected:** the line number next to that test highlights, or the whole test highlights, or _something_ happens.
**Actual:** nothing happens

**Comment by schanzer** [comment]
Update: it appears the definitions window scrolls upwards, hiding the first line from view. Still problematic, but different from what I observed a month ago.

**Comment by ds26gte** [comment]
Fixed to scroll to just above the tested expression.

**Comment by schanzer** [comment]
Note: The original issue is still open.

**Comment by ds26gte** [comment]
This isn't specific to Patch. Pyret has the same situation: viz., only failing test results have error locations that can be "vivified". That said:

I've added a feature whereby clicking a passing test result highlights the gutter line on that test with green. (Failing tests have a permanent gutter color of yellow.) Clicking the passing test result again removes the green (it's a toggle, so you can focus and unfocus on passing tests according to your interest).

**Comment by ds26gte** [comment]
P.S. Passing tests default to a gutter color of green. Clicking test result toggles between default green and blue.

**Comment by schanzer** [comment]
Nice touch!
