### ISSUE TITLE
Rotate should support negative angles

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#41]
[This program](https://drive.google.com/file/d/0BzzMl1BJlJDkdjBUblpzUjJ3Z2M/view?usp=sharing) works in WeScheme, but not in Patch.

Reported by Tiina Partnanen

**Comment by ds26gte** [comment]
Thanks; fixed. `rotate` now supports any real number of degrees as angle, internally canonicalizing it to [0, 360).
