### ISSUE TITLE
Rounding errors in graphics primitives

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#48]
See errors in http://www.wescheme.org/view?publicId=vZ7nwdNAkS

This problem almost certainly exists in CPO as well.

**Comment by schanzer** [comment]
I believe the relevant commits in WeScheme are

https://github.com/bootstrapworld/wescheme2012/commit/2992a4333ed91ef40b84f0018ae4c8a2e1e6e489 and https://github.com/bootstrapworld/wescheme2012/commit/b2ecf8994902fa31872cb4e106648031ea472798. I _really_ thought these were merged into CPO along with the on-pixel vertex placement fix last summer.

**Comment by schanzer** [comment]
Confirmed: the problem exists in Pyret

```include image

fun sierpinski(size):
  if (size <= 2):
    triangle(size, "outline","blue")
  else:
    overlay(
      triangle(size, "outline","blue"),
      above(
        sierpinski(size / 2),
        beside(sierpinski(size / 2), sierpinski(size / 2))))
  end
end```

**Comment by schanzer** [comment]
Here's at least one area where CPO diverges from the WeScheme commit in March 2016: https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/trove/image-lib.js#L767

**Comment by ds26gte** [comment]
That part actually matches, except that the wescheme version adds a `this.color` argument. The significant change seems to be in the definition of `OverlayImage`. The commits you mention seem to have undergone a lot of subsequent changes, and they are captured in CPO, except for `OverlayImage`. I'm in the process of updating.

**Comment by ds26gte** [comment]
`image-lib.js` now matches WeScheme's `world.js`: the correct `image-height` should now be shown. Note though the image still looks small but that's because Pyret has decided that it's too big to fit the pane and therefore offers it as a thumbnail.  There is a subtle border and shadow. Hovering over the thumbnail shows a magnifying-glass icon. Click the image to get full size.

**Comment by schanzer** [comment]
Beautiful! Will you be upstreaming this to CPO (it's still broken there, at least on production).
