### ISSUE TITLE
ö, ä and backspace not handled correctly in big-bang

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#52]
[submitted by Tiina Partanan, test session 3, bug 3]

ö, ä and backspace are not handled correctly by big-bang, none of these work in a simple editor
(e.g. chars are not deleted with backspace and ö and ä are not entered in the editor field like they should be)

This works in WeScheme:
http://www.wescheme.org/view?publicId=MFVPRzKH6L

**Comment by schanzer** [comment]
This is almost certainly another symptom of https://github.com/brownplt/code.pyret.org/issues/35

**Comment by ds26gte** [comment]
Fixed, by filtering `Compose` and `Backspace` events from being treated by world. (world now responds to both `keydown` and `keypress` events It may be possible to remove `keydown` completely from the mix but right now there is still dependence on it.)

Note: `Compose` is triggered by `AltGr` (the right `Alt` key). I type letters with diacritics with `AltGr` on a US keyboard, but this may not be universal. If you use some other mechanism, please let me know after first checking that the current implementation indeed doesn't work for you.

This fix is not Patch-specific. It can work for Pyret too.

**Comment by schanzer** [comment]
!!!!! 
I know this is nontrivial. Nice work! Would love to get this upstreamed. Can you make a PR?

**Comment by ds26gte** [comment]
Interestingly, the above fix isn't enough for Pyret! Pyret currently doesn't allow `\b` inside a string, and when that's fixed, it requires a further fix (in `pyret-lang`, not `code.pyret.org`) to recognize `\b` as backspace, not the `NUL` character. 

(The reason this didn't error for Patch is because the read of the Patch repl is different from the read for the Pyret repl.)

I do have the complete fix now, for both Patch and Pyret. I hope there is no legacy objection to allowing `\b` to stand for backspace in Pyret strings.

**Comment by schanzer** [comment]
Ah, interesting. Wow. Curious to know what Joe and Ben think about this...

**Comment by schanzer** [comment]
Since it's implemented in Patch, and CPO has its own issue, I'm going to close this.
