### ISSUE TITLE
Empty list: '() highlighted in red in editor  

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#53]
[submitted by Tiina P, test session 2, bug 12]

It seems that the editor is not understanding '() as a legal code (shows red) yet this is running ok (no errors).

**Comment by schanzer** [comment]
Should Patch's CM use WeScheme's scheme mode?

**Comment by ds26gte** [comment]
Fixed.  Also added recognition for Patch keywords (`begin case cond define define-struct define-values lambda λ let* local quasiquote quote unless unquote unquote-splicing`).

**Comment by schanzer** [comment]
Beautiful!

**Comment by ds26gte** [comment]
P.S. Added recognition for `;` comments. Removed `#` comments (except for `#| ... |#`), as these are not relevant for Patch.
