### ISSUE TITLE
"Pyret" files should be just "code" files?  

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#54]
[submitted by Tiina P., test session 2, bug 11]

Opening files from google-drive user is instructed to select Pyret files, this is not the case here.... Should we just call them code files, Racket files or what...? The language is not pure Racket, it is not BSL either... What is it called, I don't know, but Pyret is not the right name.

**Comment by schanzer** [comment]
How about just "files"? Or maybe "Patch files"?

**Comment by ds26gte** [comment]
Changed "Pyret document" to more agnostic "code file".

**Comment by schanzer** [comment]
LGTM! (There are some other issues related to the "open" feature, but I'll file those separately.)
