### ISSUE TITLE
Mouse clicks are not working

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#55]
[submitted by Tiina P, test session 2, bug 3]

on-mouse is no longer creating an error messages but mouse clicks still not functioning. You can test this in patch by removing the empty-scene*s "forestgreen" from this code (below). Clicking the spite should increment the score (works in wescheme).

http://www.wescheme.org/view?publicId=KHKMqfSy8w

**Comment by schanzer** [comment]
This appears to work for me in Patch. May need to cycle back to Tiina.

**Comment by ds26gte** [comment]
Yes, added fix for this.  (Needed an appropriate definition for `mouse=?`, added as `is-mouse-equal` in `world.js`.)

**Comment by schanzer** [comment]
Awesome. Then I'm confirming it as fixed, and closing.
