### ISSUE TITLE
Publish not working

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#56]
[submitted by Tiina P, test session 2, bug 5]

Should the publish button work? Now it just showed a small empty square and no link was was created....

**Comment by ds26gte** [comment]
Fixed.

This is also a Pyret bug. Happens when you a open an existing code file and try to publish it. (As opposed to pressing 'save' and then publishing it.) The `showShares` argument in that case is a promise only, whereas the function's body expects a resolved promise.

**Comment by schanzer** [comment]
Not sure I follow the technical details here, but can we upstream the fix if CPO suffers from the same thing?
