### ISSUE TITLE
Pressing space ends universe program prematurely 

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#57]
[submitted by Tiina P, test session 2, bug 6]

This ufo animation is stopped prematurely when space bar is pressed during animation, in wescheme this program runs ok until ufo touches ground (space bar presses ignored like they should be).

http://www.wescheme.org/view?publicId=Uz3YJjfPUG

**Comment by jpolitz** [comment]
I see what's happening, though I'm not sure if new or not.  The "X" button in the dialog starts as highlighted, and space triggers pressing it.  If you click off of the "X", and then press space, the key event functions normally.

We may just need to `.unfocus()` the "X" button (or `.focus()` something else) when the animation starts.

Good find.

**Comment by schanzer** [comment]
Whoa. If this is the default behavior, how does CPO handle any key events during animations? Won't all the keys fire on the "X" button, or are you doing something magical?

**Comment by jpolitz** [comment]
I'm actually a little confused; _if_ you register a key handler, the
animation appears to be focused, so this doesn't come up (I guess if it
didn't, we would have noticed a long time ago).

I'll have to find where that logic is happening to explain this better.

**Comment by ds26gte** [comment]
Here's the Pyret version of Tiina's program if you want to experiment. 

```
import image as I
import world as W

var LAHTO = 0

var UFO = I.overlay-xy(I.ellipse(120, 40, "solid", "violet"),
                     30, -25,
                     I.circle(30, "outline", "black"))

var TAUSTA = I.empty-scene(300, 500)

fun piirra-ufo(y):
  I.place-image(UFO, 150, y, TAUSTA)
end

fun pysahdy-p(y):
  y > 465
end

fun siirra-ufo(y):
  y + 3
end

W.big-bang(LAHTO, [list:
  W.to-draw(piirra-ufo),
  W.on-tick(siirra-ufo),
  W.stop-when(pysahdy-p)
])
```

**Comment by ds26gte** [comment]
Fixed.

But do note: Calling `blur()` or `focusout()` (there's no such thing as `unfocus`) and/or setting the attribute `tabIndex` to -1 doesn't do the trick -- there seems no way to lose focus via code. (You can lose focus by clicking elsewhere, which doesn't address this issue.) My solution was to disable space from triggering anything (in particular a close-window operation) on any buttons (and only buttons) within an animation window.

**Comment by schanzer** [comment]
This seems like the wrong fix entirely -- when a new animation is opened, the canvas element itself should receive `focus()` no matter what. We shouldn't have to call `blur()` on the close button.

**Comment by ds26gte** [comment]
The canvas does have the focus and the active element is its close button. Pressing space was equivalent to left-clicking the active element. (The "original" event which is a space keypress gets translated to a left-click mouse event.)

So I made such buttons respond only to genuine mouse-click events. I should think this addresses the stated problem exactly, with no overstepping. 

(I was _not_ implementing @jpolitz's suggestion of unfocusing the animation window.)

**Comment by jpolitz** [comment]
I think the right solution is to add `.attr('tabindex', 1).focus()` in the chain of calls for the setup of `toplevelNode`, right after it is `appendTo` the `outertopLevelNode`:

https://github.com/brownplt/code.pyret.org/blob/d77e13732a21f5f8ba7f2a9c8a34a527f4994595/src/web/js/trove/world.js#L199

This is the same logic that appears when a key handler is added:

https://github.com/brownplt/code.pyret.org/blob/d77e13732a21f5f8ba7f2a9c8a34a527f4994595/src/web/js/trove/world-lib.js#L828

I think it should just always happen, not only when key events are registered.

**Comment by jpolitz** [comment]
See https://github.com/brownplt/code.pyret.org/commit/0d43aae4d85b8f05d7f6c73a2749a55444979ccb

**Comment by ds26gte** [comment]
Thanks! Done and deployed to https://patch-editor.herokuapp.com.
