### ISSUE TITLE
universe program is not closing correclty when return key is pressed

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#59]
[submitted by Tiina P, test session 2, bug 8]

The user interface windows (universe program) should close when return (enter) key is pressed, this is not working correctly in patch (universe program is not closing or return key is not detected correclty).

This works ok in WeScheme:
http://www.wescheme.org/view?publicId=VPcpNC0fKJ

**Comment by ds26gte** [comment]
Fixed.

`getKeyCodeName` should return `\b` and `\r` (and possibly others) as themselves so programs can use `key=?` on them. Also: flag `closeWhenStop` should be initialized to `true`.

(Note: You should disable browser extensions that let you use vi-like keypresses to operate the browser, as it interferes with data entry in Patch text boxes. This was not the bug reported, but I got bit by it.)

**Comment by schanzer** [comment]
Confirmed fixed.
