### ISSUE TITLE
Scandianvian letters (ä, ö, å) not printed correclty with text function

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#63]
[submitted by Tiina P, test session 2, bug 9]

See images. Should read "Anna yksikkö" and "Hyvää yötä".

This works ok in WeScheme:
http://www.wescheme.org/view?publicId=VPcpNC0fKJ

**Comment by schanzer** [comment]
This appears to work in Patch now. Did you push a fix?

**Comment by ds26gte** [comment]
Yes, fixed.
