### ISSUE TITLE
make-list is missing (also from WeScheme)

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#64]
[submitted by Tiina P: test session 2, bug 13]

I noticed that make-list (BSL) is missing from patch AND also from WeScheme... So bug report for both of them. I am using this function, so it would help to have it in WeScheme/Patch also.

https://docs.racket-lang.org/htdp-langs/beginner.html?q=make-list#%28def._htdp-beginner._%28%28lib._lang%2Fhtdp-beginner..rkt%29._make-list%29%29 

I assume that you want to be in line with DrRacket BSL and selected parts of ISL and ASL?

**Comment by ds26gte** [comment]
`make-list` added, as also the analogous `make-string` and `make-vector`. Each of these takes two arguments: (i) the length of the sequence to be generated, and (ii) the filler element.

**Comment by schanzer** [comment]
Fixed in WeScheme as well.
