### ISSUE TITLE
difference in handling exact/inexact numbers when converting to string

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#67]
[submitted by Tiina, test session 3, bug 2]

Converting inexact number to string results in weird additional characters (unless you have specified this in a different way from WeScheme).

The following line results in different strings (see images):
(number->string (exact->inexact 4.0))

This worked in WeScheme (in Patch 2 test cases are failing):
http://www.wescheme.org/view?publicId=wvxqh0jGVN

**Comment by ds26gte** [comment]
Previously, Patch `{number->string, exact->inexact, inexact->exact}` were mapped to Pyret `{num-tostring, num-to-complexroughnum, num-to-complexrational}`. While technically correct, this gave explicitly complex numbers even for reals, which is TMI. Implementing these functions now with dedicated `{_spyret_number_to_string, _spyret_exact_to_inexact, _spyret_inexact_to_exact}` that do elide imaginary part for real arguments.

Note: `(exact->inexact 4)` produces `#i4` rather than `4.0`. Inexactness is always explicitly annotated in Patch, and is not implied by a decimal point.

Also added `{real-part, imag-part}` (equivalent to Pyret `{num-imagpart, num-realpart}`).

**Comment by schanzer** [comment]
Fantastic - and thanks for such a complete fix!
