### ISSUE TITLE
Impossible to stop a universe program (stop button inactive during universe, ESC not working either)

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#69]
[submitted by Tiina P, test session 3, bug 5]

You cannot stop a universe program using "stop" button because it is out of scope. Also ESC is not working, it is interpreted as some other key...?

This program cannot be stopped by "stop" or "ECS" in Patch (can be stopped by ESC in WeScheme):
http://www.wescheme.org/view?publicId=pSybHh7xy4

**Comment by ds26gte** [comment]
Fixed, I think, but I don't know all the situations where hitting ESCAPE is intuitive. Please check.

**Comment by schanzer** [comment]
Not sure what you mean by "intuitive" -- every big bang should reserve the ESC key, and terminate when it's pressed. It certainly appears to work in the programs I've thrown at it.
