### ISSUE TITLE
Forward-definition resolution fails

### ISSUE THREAD

**Issue by ds26gte** [ds26gte/code.pyret.org#78]
[submitted by Tiina Partanen, 2017 Apr 21]

I found one problematic piece of code (not a legacy lib issue). This regular snake game is not working in Patch but works in WeScheme (some variable definition problem, ALKU is defined before using it but it is not working...?):
http://www.wescheme.org/view?publicId=dEn9RScw6o

**Comment by ds26gte** [comment]
When rearranging top-level expressions in a program, we were identifying all the lambda defs (L), and bubbling up first all the non-lambda defs that didn't call any of the functions in L, then all the lambda defs that didn't call any of the functions in L, and keeping the others in place. This report presents a case where this was not enough.  There was a lambda-def that referred to a non-lambda-def, and the non-lambda-def did refer to another lambda-def and so wasn't bubbled. 

To solve this: we augment L with all the non-lambda-defs that refer to a lambda-def, and split the defs into four categories, in the following order: (1) non-lambda-defs that don't rely on L; (2) lambda-defs that don't rely on L; (3) non-lambda-defs that do rely on L; and (4) lambda-defs that do rely on L.  (1 and 2 are the ones bubbled up, 3 and 4 stay put.)

This example also needed another change, now that we're using both keypress and keydown events: We need to ensure that arrow keys are still treated as keydown not keypress, in order to keep using the old key names ("left", etc., rather than "ArrowLeft", etc.)

**Comment by schanzer** [comment]
Re: using keypress and keydown -- welcome to WeScheme's world
