### ISSUE TITLE
Add plot to Patch

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#79]
`; plot : (Num -> Num) -> image`

Should open a big-bang window (or something), ideally allowing some interactivity before the window is close, thereby generating the image.

**Comment by ds26gte** [comment]
Is
```
; plot : String, (Num -> Num) -> Image
```
acceptable? I.e., `plot` takes a title-string followed by the function to be plotted?

I've added this version to the current `patch-editor.herokuapp.com` . E.g.,

```
(plot "Square" sqr)
```

**Comment by schanzer** [comment]
This looks terrific. THANK YOU!
