### ISSUE TITLE
Probably trivial issue with first

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#8]
(Opening issues on CPO instead of pyret-lang, since I realize now that all the spyret development is happening here anyway)

`(define x (list 1 2 3))`
`(first x)`

Should produce 1, but instead re-prints the list

**Comment by ds26gte** [comment]
Fixed in ds26gte/pyret-lang@f76bf5b.

(Ironically, this was a bug in pyret-lang after all. :smirk:)
