### ISSUE TITLE
Evaluating in the REPL messes up screenreaders' virtual cursor

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#84]
After evaluating an expression in the REPL, the screenreader loses focus and has to be manually reset. This tends happens when the element containing the virtual cursor is deleted, which is exactly how we handle an evaluation: the evaluated expression is nuked and redrawn as a readonly CM instance. I can reliably reproduce this on my Chromebook: when evaluating an expression, the focus box jumps from the REPL textfield to the editor itself…and then to the next REPL textfield. That shows that ChromeVox is doing a better job than NVDA here, but is still stuttering because of the same problem.

**Comment by ds26gte** [comment]
Can't replicate loss of focus -- perhaps this was fixed in the rewrite in 4d7a702 which speaks commentary on each prompt interaction simultaneously as it's happening.

**Comment by schanzer** [comment]
Confirmed fixed
